// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChx_YAUfGzJltG_7RxcSk893HPyz2_n7E',
    appId: '1:638957534276:web:59d927ef72fd373c7c1011',
    messagingSenderId: '638957534276',
    projectId: 'chatku-8d8c6',
    authDomain: 'chatku-8d8c6.firebaseapp.com',
    storageBucket: 'chatku-8d8c6.appspot.com',
    measurementId: 'G-7NFHP55FCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEIBQlx-DoHBdGGSFWgi0656SpmADkeKw',
    appId: '1:638957534276:android:3477782c3420605b7c1011',
    messagingSenderId: '638957534276',
    projectId: 'chatku-8d8c6',
    storageBucket: 'chatku-8d8c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhCyduw6HyzBwTXmwN1qOctUjHzdR_5yo',
    appId: '1:638957534276:ios:592437de293c5f707c1011',
    messagingSenderId: '638957534276',
    projectId: 'chatku-8d8c6',
    storageBucket: 'chatku-8d8c6.appspot.com',
    iosBundleId: 'com.example.chatku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhCyduw6HyzBwTXmwN1qOctUjHzdR_5yo',
    appId: '1:638957534276:ios:592437de293c5f707c1011',
    messagingSenderId: '638957534276',
    projectId: 'chatku-8d8c6',
    storageBucket: 'chatku-8d8c6.appspot.com',
    iosBundleId: 'com.example.chatku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChx_YAUfGzJltG_7RxcSk893HPyz2_n7E',
    appId: '1:638957534276:web:7eec2c90a2eb52bf7c1011',
    messagingSenderId: '638957534276',
    projectId: 'chatku-8d8c6',
    authDomain: 'chatku-8d8c6.firebaseapp.com',
    storageBucket: 'chatku-8d8c6.appspot.com',
    measurementId: 'G-P0L7N2N1W8',
  );
}
